

export const CHANGE_HOME = 'CHANGE_HOME';
export const CHANGE_MAIN = 'CHANGE_MAIN';
export const CHANGE_NEWS = 'CHANGE_NEWS';
export const ERROR_LOGIN_ACTION = 'ERROR_LOGIN_ACTION';
export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN_ACTION';
export const RECEIVE_LOGIN_ACTION = 'RECEIVE_LOGIN_ACTION';


